name: Unit tests with mongo and codecov

on:
  push:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2 
      with:
        node-version: 16
    - name: Start MongoDB 🌿
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: 5.0
        mongodb-replica-set: test-rs
        mongodb-port: 42069
    - run: npm install
    - run: npm test
    - uses: codecov/codecov-action@v2
      with:
        directory: ./coverage